### ISSUE TITLE
Can we keep Original Audio of Video and overlay second audio over it.

### ISSUE THREAD

**Issue by pawaom** [linkedin/LiTr#108]
I have 2 questions

Can we keep Original Audio of Video and overlay second audio over it?

And can we add multiple audio over same video Like say Original Audio from video and Song 1 and Saong 2 overlayed over it.

**Comment by izzytwosheds** [comment]
Interesting questions, thank you for asking!

> Can we keep Original Audio of Video and overlay second audio over it?
Not yet. We don't support any audio muxing yet. 

> And can we add multiple audio over same video Like say Original Audio from video and Song 1 and Song 2 overlayed over it.
Also no. This is the same question as above - we don't support muxing yet.

Muxing audio is not a very straightforward task, because it requires a lot of prerequisite work to do it properly, such as changing audio sampling rate, adjusting gain, etc. It is on my TODO list, but to be honest, not very high on it, since it is a lot of effort for something that is not a lot of people are asking for.

**Comment by pawaom** [comment]
can you provide a sample how to use it, I looked into the code, and `AudioOverlayFilter` is never used in the demo.

**Comment by izzytwosheds** [comment]
It is very straightforward. I added its usage to sample app: https://github.com/linkedin/LiTr/blob/main/litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TranscodeVideoGlPresenter.kt#L121

**Comment by pawaom** [comment]
can you please explain the logic that you have used in AudioOverlayFilter, I have been trying to implement it for along time, without success, specially how do you manage to add multiple audios over each other or mix two audio file and create a new audio file and write that to video.

**Comment by izzytwosheds** [comment]
The hard part in audio mixing is to make all audio tracks same format - channel count + sampling rate. I had to pull in Oboe library to achieve that. Once that is done, actual mixing is simply adding up 16-bit short values of different audio buffers. `AudioOverlayFilter` does that plus manages reading and decoding overlay audio frames.

**Comment by pawaom** [comment]
can we overlay multiple audios to one video , also how to change the start point and end point of audio, for example if we have a 2 minute long video and we want to add a clip from and audio which is 3 minutes long, the clip starting from 15th second to 30 the second, also can we loop the audio over the duration of the video or say from the 60th second of video to 90th second.

**Comment by pawaom** [comment]
Can we change volume of the overlay audio in the demo there is option to change video volume but not for the overlay  audio

**Comment by pawaom** [comment]
Thanks my other question about volume control, can we do that?

**Comment by pawaom** [comment]
I am trying this code 


```
public class TranscodeActivity extends AppCompatActivity  {
    SourceMedia sourceMedia = new SourceMedia();
    private static final int PICK_MEDIA = 42;

    private static final String KEY_ROTATION = Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
            ? MediaFormat.KEY_ROTATION
            : "rotation-degrees";

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.frag2);

        Uri videoUri = Uri.parse("content://media/external/video/media/931");
        updateSourceMedia(videoUri);
        Uri audioUri = Uri.parse("content://media/external/audio/media/54");
        updateSourceMedia(audioUri);
        Button TransFormButton = (Button) findViewById(R.id.TransformButton);
        TransFormButton.setOnClickListener(view -> {
            File targetFile = new File(TransformationUtil.getTargetFileDirectory(Frag2.this.getApplicationContext()),
                    "transcoded_" + TransformationUtil.getDisplayName(Frag2.this, sourceMedia.uri));

            TargetMedia targetMedia =  new TargetMedia();
            targetMedia.setTargetFile(targetFile);
            targetMedia.setTracks(sourceMedia.tracks);
            TransformationState transformationState =    new TransformationState();
            transformationState.setState(TransformationState.STATE_RUNNING);
            startTransformation(sourceMedia,targetMedia,transformationState);
        });

    }

    private MediaTransformer mediaTransformer = null;

    public void startTransformation(@NonNull SourceMedia sourceMedia,
                                    @NonNull TargetMedia targetMedia,
                                    @NonNull TransformationState transformationState) {
        mediaTransformer = new MediaTransformer(Frag2.this.getApplicationContext());
        if (targetMedia.getIncludedTrackCount() < 1) {
            return;
        }
        if (targetMedia.targetFile.exists()) {
            targetMedia.targetFile.delete();
        }
        transformationState.requestId = UUID.randomUUID().toString();
        MediaTransformationListener transformationListener = new MediaTransformationListener(Frag2.this,
                transformationState.requestId,
                transformationState,
                targetMedia);
        try {
            int videoRotation = 0;
            for (MediaTrackFormat trackFormat : sourceMedia.tracks) {
                if (trackFormat.mimeType.startsWith("video")) {
                    videoRotation = ((VideoTrackFormat) trackFormat).rotation;
                    break;
                }
            }
            MediaTarget mediaTarget = new MediaMuxerMediaTarget(
                    Frag2.this,
                    Uri.fromFile(targetMedia.targetFile),
                    targetMedia.getIncludedTrackCount(),
                    videoRotation,
                    0);
            List<TrackTransform> trackTransforms = new ArrayList<>(targetMedia.tracks.size());
            MediaRange mediaRange;
            mediaRange = new MediaRange(0, Long.MAX_VALUE);
            MediaSource mediaSource = new MediaExtractorMediaSource(Frag2.this, sourceMedia.uri, mediaRange);
            for (TargetTrack targetTrack : targetMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }
                Encoder encoder = new MediaCodecEncoder();
                TrackTransform.Builder trackTransformBuilder = new TrackTransform.Builder(mediaSource,
                        targetTrack.sourceTrackIndex,
                        mediaTarget)
                        .setTargetTrack(trackTransforms.size())
                        .setTargetFormat(targetTrack.shouldTranscode ? createMediaFormat(targetTrack) : null)
                        .setEncoder(encoder)
                        .setDecoder(new MediaCodecDecoder());
                if (targetTrack.format instanceof VideoTrackFormat) {
                    trackTransformBuilder.setRenderer(new GlVideoRenderer(createGlFilters(sourceMedia,
                            (TargetVideoTrack) targetTrack,
                            0.56f,
                            new PointF(0.6f, 0.4f),
                            30)));
                } else if (targetTrack.format instanceof AudioTrackFormat && targetTrack.overlay != null) {
                    trackTransformBuilder.setRenderer(
                            new AudioRenderer(
                                    encoder,
                                    Collections.singletonList(new AudioOverlayFilter(Frag2.this, targetTrack.overlay))
                            )
                    );
                }
                trackTransforms.add(trackTransformBuilder.build());
            }
            mediaTransformer.transform(transformationState.requestId,
                    trackTransforms,
                    transformationListener,
                    MediaTransformer.GRANULARITY_DEFAULT);
        } catch (MediaTransformationException ex) {
            Log.e(TAG, "Exception when trying to perform track operation", ex);
        }
    }

    @Nullable
    private MediaFormat createMediaFormat(@Nullable TargetTrack targetTrack) {
        MediaFormat mediaFormat = null;
        if (targetTrack != null && targetTrack.format != null) {
            if (targetTrack.format.mimeType.startsWith("video")) {
                mediaFormat = createVideoMediaFormat((VideoTrackFormat) targetTrack.format);
            } else if (targetTrack.format.mimeType.startsWith("audio")) {
                mediaFormat = createAudioMediaFormat((AudioTrackFormat) targetTrack.format);
            }
        }
        return mediaFormat;
    }

    @NonNull
    private MediaFormat createVideoMediaFormat(@NonNull VideoTrackFormat trackFormat) {
        MediaFormat mediaFormat = new MediaFormat();
        mediaFormat.setString(MediaFormat.KEY_MIME, trackFormat.mimeType);
        mediaFormat.setInteger(MediaFormat.KEY_WIDTH, trackFormat.width);
        mediaFormat.setInteger(MediaFormat.KEY_HEIGHT, trackFormat.height);
        mediaFormat.setInteger(MediaFormat.KEY_BIT_RATE, trackFormat.bitrate);
        mediaFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, trackFormat.keyFrameInterval);
        mediaFormat.setInteger(MediaFormat.KEY_FRAME_RATE, trackFormat.frameRate);
        mediaFormat.setLong(MediaFormat.KEY_DURATION, trackFormat.duration);
        mediaFormat.setInteger(KEY_ROTATION, trackFormat.rotation);
        return mediaFormat;
    }

    @Nullable
    private List<GlFilter> createGlFilters(@NonNull SourceMedia sourceMedia,
                                           @Nullable TargetVideoTrack targetTrack,
                                           float overlayWidth,
                                           @NonNull PointF position,
                                           float rotation) {
        List<GlFilter> glFilters = null;
        if (targetTrack != null && targetTrack.overlay != null) {
            try {
                Bitmap bitmap = BitmapFactory.decodeStream(Frag2.this.getContentResolver().openInputStream(targetTrack.overlay));
                if (bitmap != null) {
                    float overlayHeight;
                    VideoTrackFormat sourceVideoTrackFormat = (VideoTrackFormat) sourceMedia.tracks.get(targetTrack.sourceTrackIndex);
                    if (sourceVideoTrackFormat.rotation == 90 || sourceVideoTrackFormat.rotation == 270) {
                        float overlayWidthPixels = overlayWidth * sourceVideoTrackFormat.height;
                        float overlayHeightPixels = overlayWidthPixels * bitmap.getHeight() / bitmap.getWidth();
                        overlayHeight = overlayHeightPixels / sourceVideoTrackFormat.width;
                    } else {
                        float overlayWidthPixels = overlayWidth * sourceVideoTrackFormat.width;
                        float overlayHeightPixels = overlayWidthPixels * bitmap.getHeight() / bitmap.getWidth();
                        overlayHeight = overlayHeightPixels / sourceVideoTrackFormat.height;
                    }
                    PointF size = new PointF(overlayWidth, overlayHeight);
                    GlFilter filter = TransformationUtil.createGlFilter(Frag2.this,
                            targetTrack.overlay,
                            size,
                            position,
                            rotation);
                    if (filter != null) {
                        glFilters = new ArrayList<>();
                        glFilters.add(filter);
                    }
                }
            } catch (IOException ex) {
                Log.e(TAG, "Failed to extract audio track metadata: " + ex);
            }
        }
        return glFilters;
    }

    @NonNull
    private MediaFormat createAudioMediaFormat(@NonNull AudioTrackFormat trackFormat) {
        MediaFormat mediaFormat = new MediaFormat();
        mediaFormat.setString(MediaFormat.KEY_MIME, trackFormat.mimeType);
        mediaFormat.setInteger(MediaFormat.KEY_CHANNEL_COUNT, trackFormat.channelCount);
        mediaFormat.setInteger(MediaFormat.KEY_SAMPLE_RATE, trackFormat.samplingRate);
        mediaFormat.setInteger(MediaFormat.KEY_BIT_RATE, trackFormat.bitrate);
        mediaFormat.setLong(MediaFormat.KEY_DURATION, trackFormat.duration);
        return mediaFormat;
    }

    protected void updateSourceMedia(@NonNull Uri uri) {
        sourceMedia.uri = uri;
        sourceMedia.size = TranscoderUtils.getSize(Frag2.this, uri);
        sourceMedia.duration = getMediaDuration(uri) / 1000f;
        try {
            MediaExtractor mediaExtractor = new MediaExtractor();
            mediaExtractor.setDataSource(Frag2.this, uri, null);
            sourceMedia.tracks = new ArrayList<>(mediaExtractor.getTrackCount());
            for (int track = 0; track < mediaExtractor.getTrackCount(); track++) {
                MediaFormat mediaFormat = mediaExtractor.getTrackFormat(track);
                String mimeType = mediaFormat.getString(MediaFormat.KEY_MIME);
                if (mimeType == null) {
                    continue;
                }
                if (mimeType.startsWith("video")) {
                    VideoTrackFormat videoTrack = new VideoTrackFormat(track, mimeType);
                    videoTrack.width = getInt(mediaFormat, MediaFormat.KEY_WIDTH);
                    videoTrack.height = getInt(mediaFormat, MediaFormat.KEY_HEIGHT);
                    videoTrack.duration = getLong(mediaFormat, MediaFormat.KEY_DURATION);
                    videoTrack.frameRate = MediaFormatUtils.getFrameRate(mediaFormat, -1).intValue();
                    videoTrack.keyFrameInterval = MediaFormatUtils.getIFrameInterval(mediaFormat, -1).intValue();
                    videoTrack.rotation = getInt(mediaFormat, KEY_ROTATION, 0);
                    videoTrack.bitrate = getInt(mediaFormat, MediaFormat.KEY_BIT_RATE);
                    sourceMedia.tracks.add(videoTrack);
                } else if (mimeType.startsWith("audio")) {
                    AudioTrackFormat audioTrack = new AudioTrackFormat(track, mimeType);
                    audioTrack.channelCount = getInt(mediaFormat, MediaFormat.KEY_CHANNEL_COUNT);
                    audioTrack.samplingRate = getInt(mediaFormat, MediaFormat.KEY_SAMPLE_RATE);
                    audioTrack.duration = getLong(mediaFormat, MediaFormat.KEY_DURATION);
                    audioTrack.bitrate = getInt(mediaFormat, MediaFormat.KEY_BIT_RATE);
                    sourceMedia.tracks.add(audioTrack);
                } else {
                    sourceMedia.tracks.add(new GenericTrackFormat(track, mimeType));
                }
            }
        } catch (IOException ex) {
            Log.e(TAG, "Failed to extract sourceMedia", ex);
        }
        sourceMedia.notifyChange();
    }

    private int getInt(@NonNull MediaFormat mediaFormat, @NonNull String key) {
        return getInt(mediaFormat, key, -1);
    }

    private int getInt(@NonNull MediaFormat mediaFormat, @NonNull String key, int defaultValue) {
        if (mediaFormat.containsKey(key)) {
            return mediaFormat.getInteger(key);
        }
        return defaultValue;
    }

    private long getLong(@NonNull MediaFormat mediaFormat, @NonNull String key) {
        if (mediaFormat.containsKey(key)) {
            return mediaFormat.getLong(key);
        }
        return -1;
    }

    private long getMediaDuration(@NonNull Uri uri) {
        MediaMetadataRetriever mediaMetadataRetriever = new MediaMetadataRetriever();
        mediaMetadataRetriever.setDataSource(Frag2.this, uri);
        String durationStr = mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);
        return Long.parseLong(durationStr);
    }

}
```

 **I am getting  this Error**

```

Transformation job error
 java.lang.IllegalStateException: Failed to add the track to the muxer
  at android.media.MediaMuxer.nativeAddTrack(Native Method)
at android.media.MediaMuxer.addTrack(MediaMuxer.java:658)
at com.linkedin.android.litr.io.MediaMuxerMediaTarget.addTrack(MediaMuxerMediaTarget.java:116)
at com.linkedin.android.litr.transcoder.PassthroughTranscoder.processNextFrame(PassthroughTranscoder.java:79)
at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:211)
at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:108)
at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
```
**Can you please help how the SourceMedia is passed to transcode?**
