### ISSUE TITLE
Facing issue in android 8 and android 9 during calling Mux Video and Audio Tracks.

### ISSUE THREAD

**Issue by amitagnihotri** [linkedin/LiTr#132]
Hello @izzytwosheds 

Facing issue in android 8 and android 9 during calling Mux Video and Audio Tracks.

Error:
E/TransformationJob: Transformation job error
com.linkedin.android.litr.exception.TrackTranscoderException: Failed to configure encoder codec.Media transformation failed for job id: null
Media format: {mime=video/avc, frame-rate=18, color-format=2130708361, height=720, width=1280, profile=1, bitrate=14641839, durationUs=10024611, i-frame-interval=5}
Diagnostic info: null
at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:217)
at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:41)
at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:74)
at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.(VideoTrackTranscoder.java:64)
at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:78)
at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:175)
at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:97)
at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.IllegalStateException
at com.linkedin.android.litr.utils.CodecUtils.createAndConfigureCodec(CodecUtils.java:283)
at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodecByType(CodecUtils.java:230)
at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:205)

    Can you please check? And guide us

**Comment by izzytwosheds** [comment]
Can you try with target `MediaFormat` with frame rate 30 and without profile value?

**Comment by amitagnihotri** [comment]
Okay I will check

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds 
I have check frame rate and profile value under MediaFormat. I m little confuse where I will change the value.

I m running LiTr demo under Mux Video and Audio Track feature.
when I m running this code android 7,8 and Android 9 Versions devices our app is crashing. Can you please check our main demo. If you fixed this issue in main Demo then i will check where you change the value of frame rate and profile value. 
It important this demo will working every devices and version of android. For now this will working fine Android 10 and 11 versions of devices. Sorry again i m putting you to write the code for below versions again. But its request if you write and then i will check and its saved our a lot of time.

**Comment by izzytwosheds** [comment]
Is this happening on the same device with different OS versions or different devices with different OS versions?

**Comment by amitagnihotri** [comment]
Actually  we have 5 plus devices and one device android 8 version and one device android 9 version and one device android 7 version and android device android 10 version and one device android 11.
Like your demo code working only android 10 and android 11 version only. It not working android 7,8 and 9 Versions of android OS. This is our issue. when we run our app android 7,8 and 9 OS version of android then we received above error.
I think this issue related to your job service. Job Service introducing in android 10 properly that  why job service working fine in android 10 and android 11.

Rest please check your code and try to run android 7.8 and 9 OS versions of android then you see the same error.

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds 

Any Update?
its really important to solve above problem Mux Video and Audio Tracks for all android versions.
Example:
Android 7, Android 8, Android 9, Android 10 and Android 11.
Please check your demo and fix this.

Thanks

**Comment by izzytwosheds** [comment]
I pushed a fix that might help. Can you try with the latest main branch?

**Comment by amitagnihotri** [comment]
Okay I will check.
Thanks
