### ISSUE TITLE
Encoder/Decoder Was not released after transform

### ISSUE THREAD

**Issue by inwady** [linkedin/LiTr#148]
I used MP4Composer before, but recently I decided to try your library (thank you much for this library, cool work).

Due to `release` problems I cannot work with ExoPlayer. I have error:
```
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:226) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

I suggest you need to do something like in library:
```
try {
                if (videoComposer != null) {
                    videoComposer.release();
                    videoComposer = null;
                }
                if (audioComposer != null) {
                    audioComposer.release();
                    audioComposer = null;
                }
                if (mediaExtractor != null) {
                    mediaExtractor.release();
                    mediaExtractor = null;
                }
               ...
```

But now `Litr` calls only `executorService.shutdownNow()`. I think this is not enough :(

### Why am I sure?

With MP4Composer there was not the bug.

**Comment by inwady** [comment]
I mean this place:
https://github.com/linkedin/LiTr/blob/648b57bf54a56abe581b8fb9769402ba0e7e2fce/litr/src/main/java/com/linkedin/android/litr/TransformationJob.java#L233

User cannot control encoder/decoder if using this params to work with your library:
```
mediaTransformer.transform(requestId,
                           sourceVideoUri,
                           targetVideoFilePath,
                           targetVideoFormat,
                           targetAudioFormat,
                           videoTransformationListener,
                           transformationOptions);
```
