### ISSUE TITLE
bug in handling InsufficientDiskSpaceException

### ISSUE THREAD

**Issue by mikeshuttjuvo** [linkedin/LiTr#178]
**Conditions:**
Using the MediaTransformer to transform a video.  The device does not have enough storage space available to store the transformed video file (i.e., the source video file is 20MB, the device only has 10MB of storage available).
 
**Expected behavior:**
An InsufficientDiskSpaceException is returned via the onError method in the TransformationListener callback interface

**Actual behavior:**
The TransformationListener.onError callback is never called.  Logging contains an entry like the following:

E/TransformationJob: Transformation job error
    com.linkedin.android.litr.exception.InsufficientDiskSpaceException: Insufficient disk space, estimated file size in bytes 1197122, available disk space in bytes 0Media transformation failed for job id: null
        at com.linkedin.android.litr.TransformationJob.verifyAvailableDiskSpace(TransformationJob.java:159)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:96)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.Throwable
        at com.linkedin.android.litr.TransformationJob.verifyAvailableDiskSpace(TransformationJob.java:159) 
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:96) 
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)

The issue appears to be a bug in the release(boolean success) method of the TransformJob class.  
 
    class TransformationJob implements Runnable { 
        ...
        void transform() throws MediaTransformationException {
            initStatsCollector();
            verifyAvailableDiskSpace();  // <-- this is called before the trackTranscoders instance variable is initialized
            createTrackTranscoders();
            startTrackTranscoders();
            seekToMediaRangeStart();
            ... do the transformation ...
        }
        ...
        void release(boolean success) {
            for (int track = 0; track < trackTranscoders.size(); track++) {  // <-- trackTranscoders is null
                TrackTranscoder trackTranscoder = trackTranscoders.get(track);
                trackTranscoder.stop();
                statsCollector.setTargetFormat(track, trackTranscoder.getTargetMediaFormat());
            }
            ...
       }
       ...
    }

The check for available disk space is called before the trackTranscoders are created.  The InsufficientDiskSpaceException thrown by the verifyAvailableDiskSpace causes the release method to be called, which in turn throws an exception because the trackTranscoders is null.

**Comment by izzytwosheds** [comment]
Nice find! And thank you for the patch. Accepted and merged.
