### ISSUE TITLE
`onMediaFormatChanged` is not working in real cases

### ISSUE THREAD

**Issue by inwady** [linkedin/LiTr#188]
Hello,

I found that there is audio formats (in video) which call `onMediaFormatChanged` with changed parameters. Unfortunately, this call breaks AudioProcessor, because parameters aren't passed. Oboe and my audio processor have bugs (100% cases). One of exception:
```
com.noomeera.numbersarcitecturetest E/AndroidRuntime: FATAL EXCEPTION: Thread-18
    Process: com.noomeera.numbersarcitecturetest, PID: 4107
    java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:515)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:216)
        at com.linkedin.android.litr.render.AudioRenderer$RenderThread.renderFrame(AudioRenderer.kt:146)
        at com.linkedin.android.litr.render.AudioRenderer$RenderThread.run(AudioRenderer.kt:116)
```

It's similar for iOS (here: https://stackoverflow.com/questions/60801572/avaudiofile-writefrom-fails-when-buffer-contains-interleaved-audio/60802378#60802378).

Nowdays, Im trying to fix it. `Inshot` and different applications have problems the same. I tested on any exported video from tiktok. [Mp4Composer-android](https://github.com/MasayukiSuda/Mp4Composer-android) contains bugs too.

BTW, feature request: make several AudioProcessors which can set from client side like in ExoPlayer :)

**Comment by izzytwosheds** [comment]
I love the idea of switching `AudioProcessor` when `onMediaFormatChanged` is called. Should be a pretty simple change, probably as simple as moving `audioProcessor` creation in `AudioRenderer` from `init` into `onMediaFormatChanged`. Do you want to give it a try and let me know if it works?

**Comment by izzytwosheds** [comment]
1. I think we should be able to resolve this with making sure that `AudioRenderer` produces audio frames with exact same format (sample rate, bitrate, channel count, etc.), which `MediaTarget` expects. 
2. Yeah, I think we should modify code to handle this.
Can you find some audio samples that have this behavior? I will look into this on my end, when I get some free time.

**Comment by inwady** [comment]
I exported two videos from TikTok. The second crash demo app. Here is the source file: https://drive.google.com/file/d/1itUpD1HrRdTMwTH2hyIyCwIEX0R3G6u7/view?usp=sharing.

And I debugged LiTr in `onMediaFormatChanged` (in series):

![telegram-cloud-photo-size-2-5402575899657877967-y](https://user-images.githubusercontent.com/5415605/164034989-a057c1b2-1e60-4c79-9c1f-54bb46eb17f4.jpg)

![telegram-cloud-photo-size-2-5402575899657877968-y](https://user-images.githubusercontent.com/5415605/164035009-f3bbae65-da30-423f-822b-0b43f2295200.jpg)

The channel count was changed. Info from ffprobe:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/5415605/164035219-bc0eb852-d3a7-42e3-80d6-9beed770d0d9.png">

For repeat just enable:

![telegram-cloud-photo-size-2-5402575899657877974-y](https://user-images.githubusercontent.com/5415605/164035355-9553768c-5fdb-4bca-a982-ace4eaee8c42.jpg)

The next exception:

![telegram-cloud-photo-size-2-5402575899657877972-y](https://user-images.githubusercontent.com/5415605/164035447-e15ac2e9-4b57-458a-ac58-bc6c317db7f2.jpg)

**Comment by inwady** [comment]
Error in Oboe:

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/5415605/164036867-28a581b8-cf26-40b1-987e-3556467139b9.png">

I fix these errors but got noises in final video or potential error here (1 of 4 same transforms):

```
    java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:515)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:216)
        at com.linkedin.android.litr.render.AudioRenderer$RenderThread.renderFrame(AudioRenderer.kt:146)
        at com.linkedin.android.litr.render.AudioRenderer$RenderThread.run(AudioRenderer.kt:116)
```

**Comment by inwady** [comment]
Today I combined MP4Compose for audio transcoder and LiTr for video transcoder. It's working. I assume this transcoder is more adopted for fixing such issues.

**Comment by izzytwosheds** [comment]
Yes, I was able to reproduce the problem. Thank you for sharing the video. I am working on fixing this now.

**Comment by izzytwosheds** [comment]
New 1.5.1 release has a fix for this issue. Let me know if it doesn't work. Closing this issue for now.
