### ISSUE TITLE
Crash Occurs while trimming H.264/AAC videos 

### ISSUE THREAD

**Issue by Manish-Microsoft** [linkedin/LiTr#226]
**Below is the stack trace of the crash** 

Seems like VideoTrackTranscoder is unable to configure the codec.

android.media.MediaCodec$CodecException: Error 0xffffec77
    at android.media.MediaCodec.native_configure(MediaCodec.java)
    at android.media.MediaCodec.configure(MediaCodec.java:1943)
    at android.media.MediaCodec.configure(MediaCodec.java:1872)
    at e.j.a.a.n.c.a(CodecUtils.java:1)
    at e.j.a.a.n.c.f(CodecUtils.java:7)
    at e.j.a.a.n.c.d(CodecUtils.java:7)
    at e.j.a.a.g.e.i(MediaCodecEncoder.java:3)
    at e.j.a.a.m.e.j(VideoTrackTranscoder.java:5)
    at e.j.a.a.m.e.<init>(VideoTrackTranscoder.java:8)
    at e.j.a.a.m.d.a(TrackTranscoderFactory.java:5)
    at e.j.a.a.d.b(TransformationJob.java:12)
    at e.j.a.a.d.j(TransformationJob.java:3)
    at e.j.a.a.d.run(TransformationJob.java:1)

What might be the cause here?

**Comment by izzytwosheds** [comment]
What is target video format sent to LiTr? Does it have a frame rate key?

**Comment by Manish-Microsoft** [comment]
the TargetVideoFormat is same as input video format

**Comment by izzytwosheds** [comment]
It is possible that input video format is missing a required parameter for frame rate. Can you debug and check?
