### ISSUE TITLE
"No decoder found" for Pixel API33-recorded videos

### ISSUE THREAD

**Issue by Rakatan** [linkedin/LiTr#255]
Hello,

First of all, thank you for all your hard work! 

I have been using your library to trim videos and have encountered the following issue:

**Library Version:** 1.5.5

**Video used in all instances:**
Shot with the default camera on a Pixel 6 running Android 13

**Video details:**
 - **Size:** 26,432,412 bytes
 - **Dimensions:** 1080×1920
 - **Codecs:** HEVC, AAC
 - **Colour Profile:** HD (1-1-1)
 - **Duration:** 11 seconds
 - **Audio channels:** Stereo

I have been unable to start processing on the same device that recorded it: **Pixel 6 API 33**

Error:
```
Transformation job error
com.linkedin.android.litr.exception.TrackTranscoderException: No decoder found.Media transformation failed for job id: [jobId]
Media format: {track-id=1, durationUs=10664266, mime=application/meta, language=```, max-input-size=113}
    
    at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:207)
    at com.linkedin.android.litr.codec.MediaCodecDecoder.init(MediaCodecDecoder.java:34)
    at com.linkedin.android.litr.transcoder.AudioTrackTranscoder.initCodecs(AudioTrackTranscoder.java:60)
    at com.linkedin.android.litr.transcoder.AudioTrackTranscoder.<init>(AudioTrackTranscoder.java:50)
    at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:91)
    at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:175)
    at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:97)
    at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

This error seems interestingly related to configuring an audio track codec, so I've ignored the audio track and this was the result:

```
Transformation job error
com.linkedin.android.litr.exception.TrackTranscoderException: No decoder found.Media transformation failed for job id: null
Media format: {track-id=1, durationUs=10664266, mime=application/meta, language=```, max-input-size=113}

    at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:207)
    at com.linkedin.android.litr.codec.MediaCodecDecoder.init(MediaCodecDecoder.java:34)
    at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:78)
    at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:69)
    at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:78)
    at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:175)
    at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:97)
    at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

I am not manipulating anything but the duration of the video in my configs of the TrackTransforms, so I'm not sure what configuration might cause this codec initialisation error. I will provide any extra details if they're requried.

Thank you!

**Comment by izzytwosheds** [comment]
Looks like your video has a metadata track, which LiTr (for some reason) is recognizing as audio and is trying to transcode. This is very weird. Could you share your video with me? You can use Google Drive or something. 
As a workaround, you can skip all non-audio or video tracks entirely when creating a `List<TrackTransform>`, I am pretty sure that will take of this problem.

**Comment by izzytwosheds** [comment]
Phew, you had me worried there for a minute. 😅 
Closing this issue for now. Let me know if you need help with anything else or find a bug. Thank you for using LiTr!
