### ISSUE TITLE
TrackTranscoderException

### ISSUE THREAD

**Issue by JesseWuuu** [linkedin/LiTr#280]
I found that compressing most videos works fine during use, but some videos may report errors。

[OMX.hisi.video.encoder.avc] failed to set input port definition parameters.
[OMX.hisi.video.encoder.avc] configureCodec returning error -1010
signalError(omxError 0x80001001, internalError -1010)
Codec reported err 0xfffffc0e, actionCode 0, while in state 3/CONFIGURING
configure failed with err 0xfffffc0e, resetting...
Codec reported err 0xffffffea, actionCode 0, while in state 3/CONFIGURING
configure failed with err 0xffffffea, resetting...
Codec reported err 0xffffffea, actionCode 0, while in state 3/CONFIGURING
configure failed with err 0xffffffea, resetting...
Transformation job error
com.linkedin.android.litr.exception.TrackTranscoderException: Failed to configure encoder codec.Media transform
Media format: {color-format=2130708361, i-frame-interval=5, durationUs=6816667, mime=video/avc, width=885, bitr
Diagnostic info: null
	at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:217)
	at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:41)
	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:76)
	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:69)
	at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:78)
	at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:175)
	at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:97)
	at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:933)
Caused by: java.lang.IllegalStateException
	at com.linkedin.android.litr.utils.CodecUtils.createAndConfigureCodec(CodecUtils.java:283)
	at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodecByType(CodecUtils.java:230)
	at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:205)
	at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:41) 
	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:76) 
	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:69) 
	at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:78) 
	at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:175) 
	at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:97) 
	at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77) 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.lang.Thread.run(Thread.java:933)

**Comment by JesseWuuu** [comment]
When I tried to compress the same video using another phone, different error messages were generated.

[OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
[OMX.qcom.video.encoder.avc] configureCodec returning error -1010
signalError(omxError 0x80001001, internalError -1010)
[OMX.qcom.video.encoder.avc] configureCodec returning error -1010
signalError(omxError 0x80001001, internalError -1010)
[TF-VIDEO]Codec reported err 0xfffffc0e/ERROR_UNSUPPORTED, actionCode 0, while in state 3/CONFIGURING
[TF-VIDEO]Codec reported err 0xfffffc0e/ERROR_UNSUPPORTED, actionCode 0, while in state 0/UNINITIALIZED
configure failed with err 0xfffffc0e, resetting...
[TF-VIDEO]Codec reported err 0xffffffea/BAD_VALUE, actionCode 0, while in state 3/CONFIGURING
configure failed with err 0xffffffea, resetting...
[TF-VIDEO]Codec reported err 0xffffffea/BAD_VALUE, actionCode 0, while in state 3/CONFIGURING
configure failed with err 0xffffffea, resetting...
failed to get ContentCatcherService.
Unhandled value -3 when receiving decoded input frame
[OMX.qcom.video.decoder.hevc] ERROR(0x80001009)
signalError(omxError 0x80001009, internalError -2147483648)
[TF-VIDEO]Codec reported err 0x80001009/-2147479543 (Unknown error 2147479543), actionCode 0, while in state 6/STARTED
freeAllBuffers: 8 buffers were freed while being dequeued!
signalError(omxError 0x80001001, internalError -2147483648)
[TF-VIDEO]Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 0/UNINITI
signalError(omxError 0x80001001, internalError -2147483648)
[TF-VIDEO]Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 0/UNINITI
signalError(omxError 0x80001001, internalError -2147483648)
[TF-VIDEO]Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 0/UNINITI
signalError(omxError 0x80001001, internalError -2147483648)
[TF-VIDEO]Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 0/UNINITI
signalError(omxError 0x80001001, internalError -2147483648)
[TF-VIDEO]Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 0/UNINITI
Transformation job error
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2976)
	at com.linkedin.android.litr.codec.MediaCodecDecoder.dequeueInputFrame(MediaCodecDecoder.java:66)
	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.extractAndEnqueueInputFrame(VideoTrackTranscoder.java
	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.processNextFrame(VideoTrackTranscoder.java:131)
	at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:211)
	at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:108)
	at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
