### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by NischalManandhar** [linkedin/LiTr#54]
I am getting `java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference` error while compressing a 4K video with details:

Video track:
- Codec: H264-MPEG-4 AVC(part 10)
- Resolution: 3840*2160
- Frame rate: 30.010

Audio track
- Sample rate: 44100 Hz
- Codec: MPEG AAC Audio
- 1 channel

I have used simple transformation api as:
`mediaTransformer.transform(
                    requestId,
                    inputUri,
                    outputFilePath,
                    targetVideoFormat,
                    null,
                    transformationListener,
                    MediaTransformer.GRANULARITY_DEFAULT,
                    null)`

`targetVideoFormat` is generated as:
`MediaFormat targetVideoFormat = new MediaFormat()

targetVideoFormat.setString(MediaFormat.KEY_MIME, "video/avc");
targetVideoFormat.setInteger(MediaFormat.KEY_WIDTH, 1920);
targetVideoFormat.setInteger(MediaFormat.KEY_HEIGHT, 1080);
targetVideoFormat.setInteger(MediaFormat.KEY_BIT_RATE, targetBitrate);
targetVideoFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 5);
targetVideoFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 30);
targetVideoFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);`

Is there anything I am missing?

**Comment by izzytwosheds** [comment]
Configuration looks right to me. Can you share a stack trace?

**Comment by NischalManandhar** [comment]
Here is the stack trace of the error encountered.
`D/TranscoderUtils: Bitrate is not available, cannot use that track to estimate size

E/TransformationJob: Transformation job error
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at android.media.MediaFormat.getInteger(MediaFormat.java:991)
        at com.linkedin.android.litr.transcoder.PassthroughTranscoder.processNextFrame(PassthroughTranscoder.java:75)
        at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:199)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:104)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by izzytwosheds** [comment]
I think this should help: https://github.com/linkedin/LiTr/pull/58
Can you try latest master with your video file and see if crash is gone?

**Comment by izzytwosheds** [comment]
Can you let me know if this fixed the crash? If it did, I will close this issue. Thank you for reporting this!

**Comment by izzytwosheds** [comment]
I also just released the new version of LiTr (1.4.0) which has this fix.

**Comment by NischalManandhar** [comment]
Thanks for the quick update. New version of LiTr (1.4.0) fixed the crash issue.
