### ISSUE TITLE
java.lang.InterruptedException

### ISSUE THREAD

**Issue by xieh123** [linkedin/LiTr#62]
I'm getting "java.lang.InterruptedException" error when i try multiple files compress.

my code:
for(String path : paths){
     ...
     mediaTransformer.transform(requestId,
                    trackTransforms,
                    transformationListener,
                    MediaTransformer.GRANULARITY_DEFAULT);
     ...
}

logcat:
 E/TransformationJob: Transformation job error
    java.lang.RuntimeException: java.lang.InterruptedException
        at com.linkedin.android.litr.render.VideoRenderInputSurface.awaitNewImage(VideoRenderInputSurface.java:118)
        at com.linkedin.android.litr.render.GlVideoRenderer.renderFrame(GlVideoRenderer.java:127)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.resizeDecodedInputFrame(VideoTrackTranscoder.java:190)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.processNextFrame(VideoTrackTranscoder.java:112)
        at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:199)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:104)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

**Comment by izzytwosheds** [comment]
Thank you for reporting this. 
Are you call `transform` method multiple times on the same instance of `MediaTransformer`, or using multiple instances of `MediaTransformer`?

**Comment by xieh123** [comment]
> Thank you for reporting this.
> Are you call `transform` method multiple times on the same instance of `MediaTransformer`, or using multiple instances of `MediaTransformer`?

Thank you for your reply. 
I'm very sorry, I called 'mMediaTransformer.release()' other code.
