### ISSUE TITLE
bufferInfo must specify a valid buffer offset, size and presentation time

### ISSUE THREAD

**Issue by behli** [linkedin/LiTr#78]
on some devices i get this error:

E/TransformationJob: Transformation job error
    java.lang.IllegalArgumentException: bufferInfo must specify a valid buffer offset, size and presentation time
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:339)
        at com.linkedin.android.litr.io.MediaMuxerMediaTarget.writeSampleData(MediaMuxerMediaTarget.java:97)
        at com.linkedin.android.litr.transcoder.AudioTrackTranscoder.writeEncodedOutputFrame(AudioTrackTranscoder.java:212)
        at com.linkedin.android.litr.transcoder.AudioTrackTranscoder.processNextFrame(AudioTrackTranscoder.java:90)
        at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:199)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:104)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

cause.getMessage() = bufferInfo must specify a valid buffer offset, size and presentation time

**Comment by behli** [comment]
this is my Media format for video 👍 
MediaFormat targetVideoFormat = new MediaFormat();
        targetVideoFormat.setString(MediaFormat.KEY_MIME, "video/avc");
        targetVideoFormat.setInteger(MediaFormat.KEY_WIDTH, resultWidth);
        targetVideoFormat.setInteger(MediaFormat.KEY_HEIGHT, resultHeight);
        targetVideoFormat.setInteger(MediaFormat.KEY_BIT_RATE, bitrate);
        targetVideoFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 5);
        targetVideoFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 25);
        targetVideoFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
       
and for audio :
MediaFormat audioVideoFormat = new MediaFormat();
        audioVideoFormat.setString(MediaFormat.KEY_MIME, MediaFormat.MIMETYPE_AUDIO_AAC);
        audioVideoFormat.setInteger(MediaFormat.KEY_BIT_RATE, 128000);
        audioVideoFormat.setInteger(MediaFormat.KEY_SAMPLE_RATE, 48000);
        audioVideoFormat.setInteger(MediaFormat.KEY_CHANNEL_COUNT, 2);

**Comment by izzytwosheds** [comment]
Thank you for reporting this! Does this happen when trimming the video? Also, would it be possible to capture the values in BufferInfo when this happens?

**Comment by behli** [comment]
this happened when transcoding videos.
how can I set the buffer offset value? 
by using targetVideoFormat?
something like :
targetVideoFormat.setInteger(MediaFormat.BUFFER_OFFSET, value);

**Comment by izzytwosheds** [comment]
You can't set that value externally. That is set internally, either by LiTr or by MediaCodec. I will look into this. 
Would it be possible to get the video you are having problems with?

**Comment by izzytwosheds** [comment]
Fix is on the way: https://github.com/linkedin/LiTr/pull/92
