### ISSUE TITLE
MediaCodecEncoder init() but throw IllegalStateException

### ISSUE THREAD

**Issue by bylijian** [linkedin/LiTr#9]
Test demo on Redmi Note 7 Android 9 :
MediaCodecEncoder, When  mediaCodec.configure ,throw IllegalStateException
 @Override
    public void init(@NonNull MediaFormat targetFormat) throws TrackTranscoderException {
        mediaCodec = null;
        ...
            if (mediaCodec != null) {
                mediaCodec.configure(targetFormat, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE);
                isReleased = false;
            } 
        ...
        } catch (IllegalStateException e) {
            if (mediaCodec != null) {
                mediaCodec.release();
                isReleased = true;
            }
        }

Iogcat:

2020-01-08 16:44:46.673 4095-4330/com.linkedin.android.litr.demo E/com.linkedin.android.litr.exception.TrackTranscoderException: Failed to retrieve media codec info.
2020-01-08 16:44:46.755 4095-4330/com.linkedin.android.litr.demo E/TransformationJob: Transformation job error
    com.linkedin.android.litr.exception.TrackTranscoderException: Failed to configure encoder codec.Media transformation failed for job id: null
    Media format: {i-frame-interval=5, durationUs=2973566, mime=video/avc, width=1280, bitrate=3300000, frame-rate=29, height=720}
    Selected media codec info: 
    Available media codec info list (Name, IsEncoder, Supported Types): 
    MediaCodecInfo: OMX.google.aac.decoder,false,[audio/mp4a-latm]
    MediaCodecInfo: OMX.google.amrnb.decoder,false,[audio/3gpp]
    MediaCodecInfo: OMX.google.amrwb.decoder,false,[audio/amr-wb]
    MediaCodecInfo: OMX.qti.audio.decoder.flac,false,[audio/flac]
    MediaCodecInfo: OMX.google.g711.alaw.decoder,false,[audio/g711-alaw]
    MediaCodecInfo: OMX.google.g711.mlaw.decoder,false,[audio/g711-mlaw]
    MediaCodecInfo: OMX.google.gsm.decoder,false,[audio/gsm]
    MediaCodecInfo: OMX.google.mp3.decoder,false,[audio/mpeg]
    MediaCodecInfo: OMX.google.opus.decoder,false,[audio/opus]
    MediaCodecInfo: OMX.google.raw.decoder,false,[audio/raw]
    MediaCodecInfo: OMX.google.vorbis.decoder,false,[audio/vorbis]
    MediaCodecInfo: OMX.google.aac.encoder,true,[audio/mp4a-latm]
    MediaCodecInfo: OMX.google.amrnb.encoder,true,[audio/3gpp]
    MediaCodecInfo: OMX.google.amrwb.encoder,true,[audio/amr-wb]
    MediaCodecInfo: OMX.google.flac.encoder,true,[audio/flac]
    MediaCodecInfo: OMX.qcom.video.decoder.avc,false,[video/avc]
    MediaCodecInfo: OMX.qcom.video.decoder.avc.secure,false,[video/avc]
    MediaCodecInfo: OMX.google.h264.decoder,false,[video/avc]
    MediaCodecInfo: OMX.qcom.video.decoder.divx,false,[video/divx]
    MediaCodecInfo: OMX.qcom.video.decoder.divx311,false,[video/divx311]
    MediaCodecInfo: OMX.qcom.video.decoder.divx4,false,[video/divx4]
    MediaCodecInfo: OMX.qcom.video.decoder.h263,false,[video/3gpp]
    MediaCodecInfo: OMX.google.h263.decoder,false,[video/3gpp]
    MediaCodecInfo: OMX.qcom.video.decoder.hevc,false,[video/hevc]
    MediaCodecInfo: OMX.qcom.video.decoder.hevc.secure,false,[video/hevc]
    MediaCodecInfo: OMX.google.hevc.decoder,false,[video/hevc]
    MediaCodecInfo: OMX.qcom.video.decoder.mpeg2,false,[video/mpeg2]
    MediaCodecInfo: OMX.qcom.video.decoder.mpeg2.secure,false,[video/mpeg2]
    MediaCodecInfo: OMX.qcom.video.decoder.mpeg4,false,[video/mp4v-es]
    MediaCodecInfo: OMX.google.mpeg4.decoder,false,[video/mp4v-es]
    MediaCodecInfo: OMX.qcom.video.decoder.vp8,false,[video/x-vnd.on2.vp8]
    MediaCodecInfo: OMX.google.vp8.decoder,false,[video/x-vnd.on2.vp8]
    MediaCodecInfo: OMX.qcom.video.decoder.vp9,false,[video/x-vnd.on2.vp9]
    MediaCodecInfo: OMX.qcom.video.decoder.vp9.secure,false,[video/x-vnd.on2.vp9]
    MediaCodecInfo: OMX.google.vp9.decoder,false,[video/x-vnd.on2.vp9]
    MediaCodecInfo: OMX.qcom.video.encoder.avc,true,[video/avc]
    MediaCodecInfo: OMX.google.h264.encoder,true,[video/avc]
    MediaCodecInfo: OMX.qcom.video.encoder.h263,true,[video/3gpp]
    MediaCodecInfo: OMX.google.h263.encoder,true,[video/3gpp]
    MediaCodecInfo: OMX.qcom.video.encoder.hevc,true,[video/hevc]
    MediaCodecInfo: OMX.qcom.video.encoder.mpeg4,true,[video/mp4v-es]
    MediaCodecInfo: OMX.google.mpeg4.encoder,true,[video/mp4v-es]
    MediaCodecInfo: OMX.qcom.video.encoder.vp8,true,[video/x-vnd.on2.vp8]
    MediaCodecInfo: OMX.google.vp8.encoder,true,[video/x-vnd.on2.vp8]
    MediaCodecInfo: OMX.google.vp9.encoder,true,[video/x-vnd.on2.vp9]Diagnostic info: android.media.MediaCodec.error_neg_2147479551
        at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:64)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:89)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:65)
        at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:59)
        at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:198)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:119)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:99)
2020-01-08 16:44:46.789 4095-4330/com.linkedin.android.litr.demo E/TransformationJob:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:48)
        	... 11 more

**Comment by izzytwosheds** [comment]
Thank you for reporting! We will work on fixing this. 
Can you try different video with a different frame rate? This one seems to be 29.97 fps video, that might be the reason for exception being thrown. Can you test with integer fps video?

**Comment by charlesannic** [comment]
Everything works fine on my Google Pixel 3 but I get the same error as @bylijian on a Samsung Galaxy A5 (SM-A510F) and on a Huawei P10 Plus (VKY-L09).

The problem occurs because the mediaCodec is null since findEncoderForFormat doesn't find any encoder on these phones. However, these are videos filmed from the phones' cameras. 

Moreover, the problem occurs even with a video having a frame rate of 30 fps.

Do you have any idea how to solve the problem, @izzytwosheds?

In any case, thanks for the great work already done! Such a library could make me drop FFmpeg and its terrible performance on Android.

**Comment by izzytwosheds** [comment]
Thanks for the update @charlesannic 
I don't have those devices locally, so not able to reproduce. I looked up specs for both devices, and it looks like they both have good hardware (Huawei can record 4K video, even) From the list of available codecs provided by @bylijian I see that there is an AVC encoder available. I don't think we are getting configuration error because hardware doesn't have enough resources to encode. My suspicion is that we might not be setting some parameter is MediaFormat we are sending, which encoder expects. 
I will try to get ahold of a device with the same chipset on my end. Can you take a look at logcat on your device and see if you are seeing any weird error messages?

**Comment by izzytwosheds** [comment]
If you guys were trying to transcode using demo app, there was a bug in the app. It was not setting default color format on the encoder. It is fixed now. Let me know if this fixes your bug.

**Comment by ppornkitpras-agoda** [comment]
I've tested the demo app on the Android emulator with normal transform and it doesn't work.

Another library (https://github.com/natario1/Transcoder/) works on the emulator fine.

```
2020-09-25 12:13:08.333 8428-8525/com.linkedin.android.litr.demo E/ACodec: [OMX.google.h264.encoder] configureCodec returning error -38
2020-09-25 12:13:08.333 8428-8525/com.linkedin.android.litr.demo E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
2020-09-25 12:13:08.333 8428-8524/com.linkedin.android.litr.demo E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
2020-09-25 12:13:08.334 8428-8523/com.linkedin.android.litr.demo E/MediaCodec: configure failed with err 0x80001001, resetting...
2020-09-25 12:13:08.336 8428-8525/com.linkedin.android.litr.demo I/OMXClient: IOmx service obtained
2020-09-25 12:13:08.339 8428-8523/com.linkedin.android.litr.demo E/com.linkedin.android.litr.exception.TrackTranscoderException: Failed to retrieve media codec info.
2020-09-25 12:13:08.341 8428-8523/com.linkedin.android.litr.demo E/TransformationJob: Transformation job error
    com.linkedin.android.litr.exception.TrackTranscoderException: Failed to configure encoder codec.Media transformation failed for job id: null
    Media format: {color-format=2130708361, i-frame-interval=5, durationUs=7102055, mime=video/avc, profile=65536, width=1280, bitrate=9848244, frame-rate=24, height=720}
    Selected media codec info: 
    Available media codec info list (Name, IsEncoder, Supported Types): 
    MediaCodecInfo: OMX.google.aac.decoder,false,[audio/mp4a-latm]
    MediaCodecInfo: OMX.google.amrnb.decoder,false,[audio/3gpp]
    MediaCodecInfo: OMX.google.amrwb.decoder,false,[audio/amr-wb]
    MediaCodecInfo: OMX.google.flac.decoder,false,[audio/flac]
    MediaCodecInfo: OMX.google.g711.alaw.decoder,false,[audio/g711-alaw]
    MediaCodecInfo: OMX.google.g711.mlaw.decoder,false,[audio/g711-mlaw]
    MediaCodecInfo: OMX.google.gsm.decoder,false,[audio/gsm]
    MediaCodecInfo: OMX.google.mp3.decoder,false,[audio/mpeg]
    MediaCodecInfo: OMX.google.opus.decoder,false,[audio/opus]
    MediaCodecInfo: OMX.google.raw.decoder,false,[audio/raw]
    MediaCodecInfo: OMX.google.vorbis.decoder,false,[audio/vorbis]
    MediaCodecInfo: OMX.google.aac.encoder,true,[audio/mp4a-latm]
    MediaCodecInfo: OMX.google.amrnb.encoder,true,[audio/3gpp]
    MediaCodecInfo: OMX.google.amrwb.encoder,true,[audio/amr-wb]
    MediaCodecInfo: OMX.google.flac.encoder,true,[audio/flac]
    MediaCodecInfo: OMX.google.h264.decoder,false,[video/avc]
    MediaCodecInfo: OMX.google.h263.decoder,false,[video/3gpp]
    MediaCodecInfo: OMX.google.hevc.decoder,false,[video/hevc]
    MediaCodecInfo: OMX.google.mpeg4.decoder,false,[video/mp4v-es]
    MediaCodecInfo: OMX.google.vp8.decoder,false,[video/x-vnd.on2.vp8]
    MediaCodecInfo: OMX.google.vp9.decoder,false,[video/x-vnd.on2.vp9]
    MediaCodecInfo: OMX.google.h264.encoder,true,[video/avc]
    MediaCodecInfo: OMX.google.h263.encoder,true,[video/3gpp]
    MediaCodecInfo: OMX.google.mpeg4.encoder,true,[video/mp4v-es]
    MediaCodecInfo: OMX.google.vp8.encoder,true,[video/x-vnd.on2.vp8]Diagnostic info: android.media.MediaCodec.error_neg_2147479551
        at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:70)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:74)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:64)
        at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:80)
        at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:171)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:94)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:54)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:74) 
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:64) 
        at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:80) 
        at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:171) 
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:94) 
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by izzytwosheds** [comment]
I was a problem in the demo app, we were trying to use highest available codec profile, which didn't work well on emulator. Removed that logic now, that should fix your problem. Let me know if it did.

**Comment by ppornkitpras-agoda** [comment]
Not using the highest profile solves the issue. Thanks!

**Comment by veljkomih** [comment]
Hi @izzytwosheds I have similar problem. I'm trying to run your lib inside my flutter project. I'm getting this as an error when encoding process starts. Do you have any idea what might be the problem?
`E/TransformationJob(10774): Transformation job error
E/TransformationJob(10774): java.lang.IllegalStateException
E/TransformationJob(10774): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/TransformationJob(10774): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
E/TransformationJob(10774): 	at com.linkedin.android.litr.codec.MediaCodecEncoder.dequeueOutputFrame(MediaCodecEncoder.java:135)
E/TransformationJob(10774): 	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.writeEncodedOutputFrame(VideoTrackTranscoder.java:213)
E/TransformationJob(10774): 	at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.processNextFrame(VideoTrackTranscoder.java:117)
E/TransformationJob(10774): 	at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:199)
E/TransformationJob(10774): 	at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:104)
E/TransformationJob(10774): 	at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74)
E/TransformationJob(10774): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/TransformationJob(10774): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/TransformationJob(10774): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TransformationJob(10774): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TransformationJob(10774): 	at java.lang.Thread.run(Thread.java:919)`

I first used lib by ypresto and then found this one which really suit my needs better.

**Comment by izzytwosheds** [comment]
@veljkomih Thank you for using LiTr!
The error you reporting is different - it happens when we try to talk to encoder, not when we are trying to create it. Does this happen in the very beginning of transcoding process? Does demo app work on your device with your input video file?

**Comment by veljkomih** [comment]
Yes, this is at the very beginning. Yes, the demo works great on my phone, that is why I wanted to use it in my flutter project, but unfortunately this happens.

**Comment by izzytwosheds** [comment]
@veljkomih Muxing multiple source on Android is not a trivial task, that is why LiTr doesn't (yet) support it. I know your pain. LiTr can still be used to transcode all your different sources into the same format. Alternatively, you can also look into using https://github.com/sannies/mp4parser to get more control over your target container.

**Comment by Hbworld** [comment]
> I was a problem in the demo app, we were trying to use highest available codec profile, which didn't work well on emulator. Removed that logic now, that should fix your problem. Let me know if it did.

@izzytwosheds hey can you specify that which logic i need to removed, I'm also getting same issue with emulator.

**Comment by Hbworld** [comment]
> Not using the highest profile solves the issue. Thanks!

@ppornkitpras-agoda hey can you specify which logic I need to remove

**Comment by izzytwosheds** [comment]
@Hbworld Make sure you are not using `CodecUtils.getHighestSupportedProfile` method and setting `KEY_PROFILE` flag in target `MediaFormat`

**Comment by Hbworld** [comment]
> @Hbworld Make sure you are not using `CodecUtils.getHighestSupportedProfile` method and setting `KEY_PROFILE` flag in target `MediaFormat`

@izzytwosheds thanks for the help
